parts:
  - name: "吴舒汀"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f18c4e12-60a3-4b3c-9010-c2288cd4512e"
  - name: "杨慧"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=97e6c3ae-870f-4907-b797-3394f014927e"
  - name: "冯浪"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=edeef6e0-b990-4d1b-bdd3-4e81bdf23fa4"
  - name: "孙嘉彤"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0b6ab4c4-fc8c-4c51-9f72-50d96c845fba"
  - name: "李晓升"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4e9b2363-dc37-4ab4-aeea-d0cab43e5e6c"
  - name: "霍佳琦"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=de036cd3-a5f4-4aed-ad85-a2799f0c17df"
  - name: "李斌"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=80d238d4-5e03-4e46-a21e-dcffaaa05637"
  - name: "罗舒文"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=832d8dd3-dd25-4531-bd2e-2c2138b7cdd9"
  - name: "谭嘉威"
    replyRobotWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=28a974f2-c387-424a-a97e-a84ed212c856"
logLevel: info
